### ISSUE TITLE
めいランチャーの起動に失敗する

### ISSUE THREAD

**Issue by mei-nico25** [MeiServer/DiscordLoginHelper#4]
ランチャー起動.batのコンソールに`Failed to access to discord`と表示され、起動に失敗する事がある。
```
2023-02-05 02:02:08 [警告]: Failed to access to discord
2023-02-05 02:02:08 [警告]: Retrying...(remain 4)
2023-02-05 02:02:10 [警告]: Failed to access to discord
2023-02-05 02:02:10 [警告]: Retrying...(remain 3)
2023-02-05 02:02:11 [警告]: Failed to access to discord
2023-02-05 02:02:11 [警告]: Retrying...(remain 2)
2023-02-05 02:02:13 [警告]: Failed to access to discord
2023-02-05 02:02:13 [警告]: Retrying...(remain 1)
2023-02-05 02:02:14 [警告]: Failed to access to discord
Exception in thread "main" java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Unknown Source)
        at r3qu13m.mei.launcher.gui.MeiLauncherGUI.loadStoredData(Unknown Source)
        at r3qu13m.mei.launcher.gui.MeiLauncherGUI.main(Unknown Source)
```
<br>

また、`Retrying`の`remain`のカウントが戻る事がある。
```
2023-02-05 01:58:31 [警告]: Failed to access to discord
2023-02-05 01:58:31 [警告]: Retrying...(remain 4)
2023-02-05 01:58:32 [警告]: Failed to access to discord
2023-02-05 01:58:32 [警告]: Retrying...(remain 3)
2023-02-05 01:58:34 [警告]: Failed to access to discord
2023-02-05 01:58:34 [警告]: Retrying...(remain 2)
2023-02-05 01:58:36 [警告]: Failed to access to discord
2023-02-05 01:58:36 [警告]: Retrying...(remain 1)
2023-02-05 01:58:37 [警告]: Failed to access to discord
2023-02-05 01:58:37 [警告]: Retrying...(remain 4)
2023-02-05 01:58:39 [情報]: Validate client jar
```
パターンも様々で、このように`1→4`の場合もあれば、`4→3→4→3→2`のような事もある。

すんなり起動する確率は数回試した感覚では70%ほど。数回リトライすれば起動はするが、長期間許容するのは厳しい頻度と判断する。

**Comment by kouch0828** [comment]
https://github.com/MeiServer/MeiServerLib/blob/61d151e32bbcb3b8cfe4555dde50aae858aee29d/src/r3qu13m/mei/lib/Discord.java#L61

ここがfalseを返すと処理がそのまま進むので結果失敗する

通信自体は成功してました(Fiddlerを間に挟んで確認。)
